turtlebot2: #namespace
  task_and_robot_environment_name: 'Hunter2Maze-v0'
  ros_ws_abspath: "/home/user/simulation_ws"
  running_step: 0.04 # amount of time the control will be executed
  pos_step: 0.016     # increment in position for each command
  
  #DDPG parameters
  alpha: 0.1
  gamma: 0.7
  epsilon: 0.9
  epsilon_discount: 0.999
  nepisodes: 500
  nsteps: 10000
  running_step: 0.06 # Time for each step

  #Environment parameters
  n_actions: 2
  n_observations: 24

  min_range: 0.5
  max_laser_value: 5.0
  min_laser_value: 0.0

  #Reward parameters
  goal_reward: 10000
  time_reward: -1

